name: Cypress + Allure Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *' # 07:00 UTC todos os dias

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Java (necessário para o Allure)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Instalar dependências
        run: npm ci

      - name: Instalar Allure CLI
        run: npm install -g allure-commandline

      - name: Executar testes com Cypress
        run: npm run e2e

      - name: Gerar relatório Allure
        run: |
          allure generate allure-results --clean -o allure-report
          allure open allure-report || echo "Falha ao abrir o relatório (ignorado no CI)"

      - name: Publicar relatório como artefato
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      - name: Notificar no Slack em caso de falha
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"❌ Testes Cypress com Allure falharam no workflow do GitHub Actions!"}' \
            ${{ secrets.SLACK_WEBHOOK }}
